version: '3'
services:
  db:
    image: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
  calc:
    build: ./calc
    volumes:
      - "./calc/:/app"
    ports:
      - 8000:5000
    depends_on:
      - db
  web:
    build: ./web
    volumes:
      - "./web/:/app"
    ports:
      - 3000:5000
    depends_on:
      - db
  scrape:
    build: ./scrape
    volumes:
      - "./scrape/:/app"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 10022:80
    depends_on:
      - db  
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=secret
volumes:
  pgdata: